replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

env:
  KAFKA_HOST: kafka.rshbdev.ru:9092
  EVENTS_COLLECTOR_TOPIC: syslog
  ALLOW_ANONYMOUS_LOGIN: yes
  ALLOW_PLAINTEXT_LISTENER: yes
  POSTGRES_SERVER: 10.7.27.113
  POSTGRES_DB: db
  POSTGRES_PORT: 5432

psvc:
  name: Сервис Событийного шлюза
  description: Сервис доступа к шлюзу событий
  istioSidecarSettings:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 50Mi
      cpu: 10m

vaultSecretKeys:
  - POSTGRES_PASSWORD
  - POSTGRES_USER

strategyType: Recreate

databases:
  - id: DATABASE_1
    type: POSTGRESQL
    host: 10.7.77.7
    port: 5432
    name: mydb

kafkaClusters:
  cluster-1:
    topics:
      syslog: